# Site settings
title: SeonDH
description: 잡다하게 쓰고 싶은 말을 적는 곳
cover: master/assets/images/bg.jpg
logo: master/assets/images/logo_SeonDH.png
favicon: master/assets/images/animal.png
homepage: "https://SeonDH.github.io/"
baseurl: "/SeonDH.github.io/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://raw.githubusercontent.com/SeonDH" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: seon.dohhyung
twitter: twitter
github:  SeonDH

#Additional Pages
home: home
about: about.md

permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: seon.dohhyung #github username
repo: SeonDH #github repository
branch: "" #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/samanyougarg/hanuman #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
